-- 1. Таблица пользователей
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL, -- 'USER', 'ADMIN'
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Таблица товаров
CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          description TEXT,
                          price NUMERIC(19, 2) NOT NULL, -- Важно: для денег используем NUMERIC, не DOUBLE!
                          stock_quantity INTEGER NOT NULL,
                          status VARCHAR(50) NOT NULL, -- 'ACTIVE', 'OUT_OF_STOCK'
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Корзина (1 юзер = 1 корзина)
CREATE TABLE carts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id BIGINT UNIQUE NOT NULL, -- UNIQUE гарантирует, что у юзера одна корзина
                       CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 4. Элементы корзины
CREATE TABLE cart_items (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            cart_id BIGINT NOT NULL,
                            product_id BIGINT NOT NULL,
                            quantity INTEGER NOT NULL CHECK (quantity > 0),
                            CONSTRAINT fk_cart_item_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
                            CONSTRAINT fk_cart_item_product FOREIGN KEY (product_id) REFERENCES products (id)
);

-- 5. Заказы
CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        total_price NUMERIC(19, 2) NOT NULL,
                        status VARCHAR(50) NOT NULL, -- 'NEW', 'PAID', 'CANCELLED'
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 6. Элементы заказа (Snapshot!)
CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             quantity INTEGER NOT NULL,
                             price_at_purchase NUMERIC(19, 2) NOT NULL, -- ФИКСИРУЕМ цену на момент покупки
                             CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
                             CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES products (id)
);

-- Индексы для ускорения поиска
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_products_status ON products(status);